apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogeyJnaGNyLmlvIjogeyJhdXRoIjoiUVZwT1JGTmxjbWRsYVRwbmFIQmZaV2c1WTJjeFUxaFJNMWh2YVdGWk9WZzJXWEJMUjB4SVZqTlRVMlZrTWtaSGFVRkcifX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjcmVkSGVscGVycyI6IHsKCQkiY29udGFpbmVyLXJlZ2lzdHJ5LmNsb3VkLnlhbmRleC5uZXQiOiAieWMiLAoJCSJjci5jbG91ZC55YW5kZXgubmV0IjogInljIiwKCQkiY3IueWFuZGV4IjogInljIgoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9
type: kubernetes.io/dockerconfigjson


