# nginx/nginx.conf
worker_processes auto;

events { worker_connections 1024; }

http {
    ###########################################################################
    # 1. Логи в JSON → попадают прямо в stdout контейнера (читает Promtail)
    ###########################################################################
    log_format json escape=json
      '{ "time":"$time_iso8601", '
      '"remote_addr":"$remote_addr", '
      '"request":"$request", '
      '"status":$status, '
      '"body_bytes_sent":$body_bytes_sent, '
      '"request_time":$request_time, '
      '"upstream_time":"$upstream_response_time", '
      '"upstream_addr":"$upstream_addr", '
      '"x_device_type":"$http_x_device_type", '
      '"agent":"$http_user_agent" }';

    access_log /dev/stdout json;
    error_log  /dev/stderr  notice;

    ###########################################################################
    # 2. Апстримы – три Go-сервиса
    ###########################################################################

    upstream mobile     { server go-mobile-bff:8082; }

    ###########################################################################
    # 3. Маршрутизация по заголовку X-Device-Type
    ###########################################################################
    map $http_x_device_type $upstream_name {
        default mobile;            # если заголовка нет
        "mobile" mobile;
    }

    ###########################################################################
    # 4. Виртуальный хост + stub_status для экспортёра метрик
    ###########################################################################
    server {
        listen 80;

        location / {
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://$upstream_name;
        }

        # для nginx-prometheus-exporter
        location /nginx_status {
            stub_status on;
            access_log   off;
            allow        127.0.0.1;   # сам nginx-exporter
            deny         all;
        }
    }
}
